spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
